### ISSUE TITLE
Xplane connected to app, but no traffic being served

### ISSUE THREAD

**Issue by amaharana** [bm98/XPVTraffic#2]
I have LiveTraffic installed in Xplane12 and connected to the app, as shown in the screenshots. However, I don't get any traffic in XPlane, and LiveTraffic confirms that it is connected but does not serve any aircraft. The status stays as "Active, serving 0 aircraft".

Is there some additional setting to tweak or action to take?

![1](https://github.com/bm98/XPVTraffic/assets/10845158/315af7b9-296d-44d5-b27a-332072acf694)
![2](https://github.com/bm98/XPVTraffic/assets/10845158/130a17e3-46cf-492f-a945-8fc0ca11a503)

**Comment by amaharana** [comment]
PS: Same result in XPlane 11. I installed the demo version and then LiveTraffic. In the app, I set base path to "D:\XPlane11" where Xplane 11 is installed and DB creation was successful. Then I established link with LiveTraffic plugin running inside XPlane 11 and got the same result - "serving 0 aircraft" and no traffic on the map.

**Comment by bm98** [comment]
RealTraffic updated their API some time ago and this caused LiveTraffic to expect something else than the prog sends...
I've updated and it seems to work at least with XP11 (I don't have XP12 to test with)
You find the update version in Releases as V 0.11
let me know..

**Comment by amaharana** [comment]
Super...works on both XPlane 11 and XPlane 12, after I recreate the DB for each version separately. What's the difference in DB for xplane 11 and 12? Any chance the same my_awy.dat could be made to work with both XP11 and XP12?

![3 - works on XPlane 11](https://github.com/bm98/XPVTraffic/assets/10845158/eaa2fea4-db22-41d4-aadd-1de4855462a8)
![3 - works on XPlane 12](https://github.com/bm98/XPVTraffic/assets/10845158/bcf316be-c34c-4c65-ab51-f76ce24b8918)

**Comment by bm98** [comment]
Glad it works again..
The my_...dat is the same for both, I don't differentiate XP11 and XP12 at all so one XPV should work with both.... I think....

**Comment by amaharana** [comment]
Got it, thank you for the work! Much appreciated.
